mc: False
is_h4l: False
input_files:
  [
    "/data/shared/hyp_run_3/pp2022/LHC22_highIR/AO2D.root",
  ]
output_dir: "../results/"
output_file: "HypertritonResults_antimatter"
selection:
  {
    "fPt": "fPt > 1",
    "fCosPA": "fCosPA > 0.99",
    "fNSigmaHe": "fNSigmaHe > -2",
    "fTPCsignalPi": "fTPCsignalPi < 1000."
  }
is_matter: "antimatter"
calibrate_he_momentum: True
skip_out_tree: False