## choose between matter, antimatter or both
matter_type: 'antimatter'

## i/o
input_parquet_data : ['../results/HypertritonResults_antimatter.parquet']
input_parquet_mc: ['../results/mc/HypertritonResults_mc_h3l_new_anch.parquet']
input_analysis_results: '/data/shared/hyp_run_3/pp2022/LHC22_highIR/AnalysisResults.root'
output_dir : '../results'
output_file : 'fit_results_antimatter.root'

is_4lh: False
preselections: ''
compute_significance: False
n_bins: 30

colliding_system: 'pp'
energy: 13.6

